// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaghnrrknhlolztvxhlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhZ2hucnJrbmhsb2x6dHZ4aGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NjA3ODgsImV4cCI6MjA4NzQzNjc4OH0.jrFLUoC-1ZawdkgYBAkDG6oKesaNxqKXGVrQp02E-dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});